### ISSUE TITLE
panic: buffered: len(pix) was 8294400 but must be 3686400

### ISSUE THREAD

**Issue by boriwo** [zergon321/reisen#1]
Hi! Thank you for this great project! I've tried your player code with your test mp4 and it works as intended. But when I try running it with any other mp4 video file I consistently get the error `panic: buffered: len(pix) was 8294400 but must be 3686400`.  I noticed the factor between those two numbers is exactly 2.25. Any idea what the issue might be here? Thank you!

**Comment by zergon321** [comment]
@boriwo As for your videos being played upside down - that shouldn't have happened. I tried my own 1920x1080 video which I got from the Internet and it works as it should. Could you please specify the output of `ffmpeg -i your_video.your_format` command? Also I would like to know where and how you obtained the video. Did you download it from the Internet or created it yourself? Did you record it using a camcorder or some 3rd party software like **OBS**? Or may be you even somehow created it yourself using your own code on some programming language?
