### ISSUE TITLE
"libavcodec/bsf.h" not found

### ISSUE THREAD

**Issue by chrplr** [zergon321/reisen#17]
Hello,

When trying to build under Ubuntu 20.04, I encounter the following error:

```
$ go build .
# github.com/zergon321/reisen
./media.go:8:11: fatal error: libavcodec/bsf.h: No such file or directory
    8 | // #include <libavcodec/bsf.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

The required libs are installed:

```
$ sudo apt install libswscale-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev
libavcodec-dev is already the newest version (7:4.2.7-0ubuntu0.1).
libavformat-dev is already the newest version (7:4.2.7-0ubuntu0.1).
libavutil-dev is already the newest version (7:4.2.7-0ubuntu0.1).
libswresample-dev is already the newest version (7:4.2.7-0ubuntu0.1).
libswscale-dev is already the newest version (7:4.2.7-0ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
But indeed, there is no `bsf.h` anywhere in `/usr/include` and subfolders. I copied `bsf.h` manually from `ffmeg/libavcodec` source code (as well as a few other needed headers), but the compilation crashes as there is always some source code missing.

No ubuntu 20.04 package seems to supply `bsf.h`:
```
$ apt-file search bsf.h
bsh-doc: /usr/share/doc/bsh-doc/html/bsf.html
libc-client2007e-dev: /usr/include/c-client/os_bsf.h
nvidia-cuda-doc: /usr/share/doc/nvidia-cuda-toolkit/html/libdevice-users-guide/__nv_fabsf.html
```

Could it be because the `libavcodec-dev`  provided by Ubuntu 20.04 is too old? Any suggestion?

**Comment by zergon321** [comment]
Hi. **Ubuntu** usually contains obsolete releases of software in its standard repositories. It means a third-party repository needs to be added in order to download the latest version of **LibAV**. Quick googling gave me `ppa:savoury1/ffmpeg4`, but I'm not sure about this one. I'm not an **Ubuntu** user myself.

**Comment by chrplr** [comment]
Many thanks ! Indeed, it now works with the ffmpeg version from this ppa.

PS: to other potential users. Beware: The creator of the ppa warns that "Upgrading FFmpeg is not recommended for beginners unless you know what you’re going to do. It may remove your applications or cause dependency issue for some multi-media apps that depends on specified version of a media library." (<https://ubuntuhandbook.org/index.php/2021/05/install-ffmpeg-4-4-ppa-ubuntu-20-04-21-04/>)
